React Lesson 8 homework
sLokhin/otus-repo-react pull request #2
Opened 2021-02-05 07:12 UTC by sLokhin

2021-02-07 08:04 UTC, sLokhin commented on src/lesson8/utils.ts
> +type GetJSONFunction = () => Promise<any>;
Как правильно описать тип, если ожидается `json`? 
`Promise<string>` только приходит в голову

2021-02-07 12:18 UTC, AntiHero requested changes

2021-02-07 12:18 UTC, AntiHero commented on src/lesson8/utils.ts
> +type GetJSONFunction = () => Promise<any>;
```
interface Comment {
  postId: number;
  id: number;
  name: string;
  email: string;
  body: string;
}
```
просто берёте тип возвращаемого объекта

2021-02-07 12:18 UTC, AntiHero commented on src/lesson8/utils.ts
> +export const getURL: GetURLFunction = (id) => {
это скорее createUrl а не get

2021-02-07 17:14 UTC, sLokhin commented on src/lesson8/MainScreen.tsx
> +  display: ${"block"};
Похоже, что в сторибуке - нет. Без такого явного указания в сторибуке верстка едет. Определяется как `inline-block`

2021-02-07 17:17 UTC, sLokhin commented on src/lesson8/MainScreen.tsx
> +interface IMainScreenProps {}
сначала было:
```
constructor({}) {
    super({});
```
но в консоле выводится предупреждение
`Warning: MainScreen(...): When calling super() in `MainScreen`, make sure to pass up the same props that your component's constructor was passed.
    in MainScreen
    in ErrorBoundary`

поэтому добавил такой тип

2021-02-07 17:19 UTC, sLokhin commented on src/lesson8/ButtonWrapper.tsx
> +  constructor(props: IButtonWrapperProps) {
попробовал убрать
```
  constructor(props: IButtonWrapperProps) {
    super(props);
    this.state = {};
  }
```
и приложение падает с ошибкой
```
ButtonWrapper.tsx:14 Uncaught TypeError: Cannot destructure 'object null' as it is null.
    at ButtonWrapper.shouldComponentUpdate (ButtonWrapper.tsx:14)
...
```

2021-02-07 17:27 UTC, sLokhin commented on src/lesson8/QuestionWindow.stories.tsx
> +      key="question-window-default"
Ок, значит `key` нужен для массива одинаковых элементов
Тогда, убрал ненужные `key` из всех `stories`

2021-02-07 17:30 UTC, sLokhin commented on src/lesson8/AnswerButton.tsx
> +import React, { FC } from "react";
здесь, видимо, имеется ввиду, чтобы отправить компонент `AnswerButton` в отдельную папку `elements` или `UI's` ?

2021-02-07 17:34 UTC, sLokhin commented on src/lesson8/MainScreen.tsx
> +    console.log(
здесь про то, что не нужны `console.log` ?
если про них, то удалил

2021-02-07 19:15 UTC, AntiHero commented on src/lesson8/ButtonWrapper.tsx
> +  constructor(props: IButtonWrapperProps) {
удалите в shouldComponentUpdate второй параметр, который nextState  `{}`, тогда всё должно заработать  без конструктора + напишите пожалуйста всем функциям на который ругается typescript-eslint типы возвращаемых значений, в Вашем случае для shouldComponentUpdate это boolean

2021-02-07 19:17 UTC, AntiHero commented on src/lesson8/MainScreen.tsx
> +interface IMainScreenProps {}
читайте подсказки typescript-eslint,  вместо этого  типа  можн использовать например Record<string, unknown>, его же можно указать и в качестве типа props в конструкторе

2021-02-07 19:18 UTC, AntiHero commented on src/lesson8/MainScreen.tsx
> +    console.log(
да, console.log лучше удалять

2021-02-07 19:19 UTC, AntiHero commented on src/lesson8/MainScreen.tsx
> +  display: ${"block"};
ок, только не понятно почему  Вы тут используете динамические строки, и в других  стилизованных компонентах тоже, разве нельзя писать просто  display: "block"?

2021-02-07 19:26 UTC, AntiHero commented on src/lesson8/AnswerButton.tsx
> +import React, { FC } from "react";
для начала  просто положить все компоненты в папку components) здорово будет если  для каждой компоненты и её тестов будет  своя отдельная  папка, тогда все свои имя_компонента.tsx Вы сможете переименовать например  в index.tsx и просто импортировать их  по названию папки,  опуская index

2021-02-08 08:26 UTC, sLokhin commented on src/lesson8/MainScreen.tsx
> +  display: ${"block"};
оказывается без кавычек надо писать, от этого ничего не работало
вот так правильно
```
const H1 = styled.h1`
  display: block;
`;
```

везде поправил

2021-02-08 13:50 UTC, AntiHero requested changes

2021-02-08 13:50 UTC, AntiHero commented on src/lesson8/components/ErrorBoundary/index.tsx
> +export class ErrorBoundary extends React.Component<{}, IErrorBoundaryState> {
```
interface IErrorBoundaryState {
  error: Error | null;
  errorInfo: React.ErrorInfo | null;
}
```

```
export class ErrorBoundary extends React.Component<
  Record<string, unknown>,
  IErrorBoundaryState
> {
  constructor(props: Record<string, unknown>) {
    super(props);
    this.state = { error: null, errorInfo: null };
  }
```

```
  componentDidCatch(error: Error, errorInfo: React.ErrorInfo): void {
    this.setState({
      error: error,
      errorInfo: errorInfo,
    });
  }
```
```
render(): React.ReactNode {
    if (this.state.errorInfo) {
      return (
        <ErrorContainer className={"error-container"}>

```

2021-02-10 14:38 UTC, merged